//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msg.FileUpload.QrCodeGenerator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QrCodeGenerator.IQrCodeGenerator")]
    public interface IQrCodeGenerator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQrCodeGenerator/Create", ReplyAction="http://tempuri.org/IQrCodeGenerator/CreateResponse")]
        string Create(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQrCodeGenerator/Create", ReplyAction="http://tempuri.org/IQrCodeGenerator/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQrCodeGeneratorChannel : Msg.FileUpload.QrCodeGenerator.IQrCodeGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QrCodeGeneratorClient : System.ServiceModel.ClientBase<Msg.FileUpload.QrCodeGenerator.IQrCodeGenerator>, Msg.FileUpload.QrCodeGenerator.IQrCodeGenerator {
        
        public QrCodeGeneratorClient() {
        }
        
        public QrCodeGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QrCodeGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QrCodeGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QrCodeGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Create(string text) {
            return base.Channel.Create(text);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(string text) {
            return base.Channel.CreateAsync(text);
        }
    }
}
